import { WalletMultiButton } from "@solana/wallet-adapter-react-ui";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Counter from "../components/Counter";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Anchor App</title>
        <meta name="description" content="Generated by create anchor app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="p-16">
        <div className="flex">
          <h1 className="pb-8 w-full">Counter Example</h1>
          <WalletMultiButton className="mb-16 bg-[#512da8]" />
        </div>
        <h2 className="pb-4">Welcome!</h2>
        <p className="pb-16 text-[#f8f8f8]">
          This is an example of using Anchor for front end Solana dapps. All of
          the logic for interacting with the blockchain is located in
          components/Counter.tsx. This project uses Next.js as the base and
          TailwindCSS for styling.
        </p>
        <h2 className="pb-4">Interact With Program</h2>
        <Counter />
      </div>
    </div>
  );
};

export default Home;
